# Generated by Django 2.0.13 on 2019-12-03 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='eventphotos')),
                ('title', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('start_day', models.DateField(default=datetime.date.today, verbose_name='Begin Day')),
                ('start_time', models.TimeField(default=datetime.time, verbose_name='Begin Time')),
                ('duration', models.DecimalField(decimal_places=1, default='1.0', max_digits=5, verbose_name='Duration')),
                ('adult_cost', models.DecimalField(decimal_places=2, default='0', max_digits=7, verbose_name='Cost for Adult')),
                ('youth_cost', models.DecimalField(decimal_places=2, default='0', max_digits=7, verbose_name='Cost for Youth')),
                ('children_cost', models.DecimalField(decimal_places=2, default='0', max_digits=7, verbose_name='Cost for Child')),
                ('description', models.TextField(max_length=1024, verbose_name='Event Description')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Event Published?')),
            ],
        ),
    ]
