# Generated by Django 2.0.13 on 2019-12-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='City', max_length=64),
        ),
    ]
