# Generated by Django 2.0.13 on 2019-12-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191204_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requirement',
            field=models.TextField(default='Enter Requirements here', max_length=1024, verbose_name='Event Requirement'),
        ),
    ]
