# Generated by Django 2.0.13 on 2019-12-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo2',
            field=models.ImageField(default='default image', null=True, upload_to='eventphotos'),
        ),
    ]
