# Generated by Django 2.0.13 on 2019-12-07 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('credit', models.CharField(max_length=128, verbose_name='Credit')),
                ('message', models.TextField(max_length=100000, verbose_name='Blog Message')),
                ('photo', models.ImageField(null=True, upload_to='blogPhotos')),
                ('category', models.CharField(max_length=128, verbose_name='Blog Category')),
                ('tags', models.CharField(max_length=128, verbose_name='Blog Tags')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='blogAuthors')),
                ('intro', models.CharField(max_length=512)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=128, verbose_name='Blog Message')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.Blog')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.BlogAuthor'),
        ),
    ]
