# Generated by Django 2.0.13 on 2019-12-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191215_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
