# Generated by Django 2.0.13 on 2019-12-16 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191215_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='commentor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
