# Generated by Django 2.0.13 on 2019-12-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191215_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='blog',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='commentor',
            field=models.IntegerField(default=-1),
        ),
    ]
