# Generated by Django 2.0.13 on 2019-12-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191215_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='blog_title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
