# Generated by Django 2.0.13 on 2019-12-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_blogcomment_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Comment Approved?'),
        ),
    ]
