# Generated by Django 2.0.13 on 2019-12-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=16)),
                ('occupation', models.CharField(blank=True, max_length=256)),
                ('message', models.TextField(max_length=128, verbose_name='Message')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='date updated')),
            ],
        ),
    ]
