# Generated by Django 2.0.13 on 2019-12-28 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo_gallery/%Y/%m/%d/')),
                ('album_cover', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('photo_album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Album')),
            ],
        ),
    ]
